# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# GitHub project page
baseurl:          /blog

# Setup
title:            PMML Cookbook
tagline:          Practical Solutions to Predictive Analytics Problems
url:              http://openscoring.io

excerpt_separator: <!-- more -->

paginate:         10

pages_list:
  About:          /about/
  Feed:           /atom.xml
