# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# GitHub project page
baseurl:          /blog

# Setup
title:            PMML in Action
tagline:          Practical Solutions to Predictive Analytics Problems
url:              http://openscoring.io

author:
  name:           Villu Ruusmann
  email:          villu.ruusmann@gmail.com

paginate:         3

pages_list:
  About:          /about/
  Archive:        /archive/
  Feed:           /atom.xml
